# Special configuration file to run tests on Travis-CI via GitHub notifications
# See https://travis-ci.org/biopython/biopython/builds for results
#
# The tests are run via the coverage script, and if the tests pass the coverage
# information is pushed to https://codecov.io/github/biopython/biopython
#
# Note when testing Python 3, the 'python' command will invoke Python 3
# and similarly for PyPy too.

# Environment variables setup via the matrix
# - DEP = list of python packages to install via default pip install
# - EXT = list of python packages to install via pip install --allow-all-external
# - BIN = list of python packages to install via pip install --only-binary
# - COV = yes/no; should tests be run with coverage metric collection
language: python
matrix:
  include:
    - python: "2.6"
      env: DEP="reportlab psycopg2 mysql-python unittest2" EXT=mysql-connector-python-rf BIN=scipy COV=yes
    - python: "2.7"
      env: DEP="reportlab psycopg2 mysql-python" EXT=mysql-connector-python-rf COV=yes
    - python: "3.3"
      env: DEP="reportlab psycopg2" EXT=mysql-connector-python-rf COV=yes
    - python: "3.4"
      env: DEP="reportlab psycopg2" EXT=mysql-connector-python-rf COV=yes
    - python: "3.5"
      env: DEP=reportlab psycopg2" EXT=mysql-connector-python-rf BIN=scipy COV=yes
    - python: "pypy"
      env: EXT="mysql-connector-python-rf" COV=yes
    - python: "pypy3"
      env: COV=no

sudo: false
addons:
  apt:
    packages:
    - bwa
    - clustalo
    - clustalw
    - emboss
    - mafft
    - muscle
    - probcons
    - samtools
    - wise

before_install:
  - "pip install --upgrade pip"
  - "pip install rdflib"
  - "pip install $DEP"
  - "pip install --only-binary=:all: $BIN"
  - "pip install --allow-all-external $EXT"
  - "if [[ $COV == 'yes' ]]; then pip install coverage; fi"


install:
#The yes is in case we get our prompt about missing NumPy
  - "/usr/bin/yes | python setup.py install"

before_script:
  - cd Tests
  - cp biosql.ini.sample biosql.ini

script:
#Using just coverage should match up to the current Python version:
  - "if [[ $COV == 'yes' ]]; then coverage run --source=Bio,BioSQL run_tests.py --offline; fi"
  - "if [[ $COV != 'yes' ]]; then python run_tests.py --offline; fi"

after_success:
#See https://codecov.io/ and https://github.com/codecov/example-python
  - "if [[ $COV == 'yes' ]]; then pip install codecov; fi"
  - "if [[ $COV == 'yes' ]]; then codecov; fi"

#The email defaults are too talkative
notifications:
  email: false
